--Using an Admin Role
USE ROLE ACCOUNTADMIN;

--Creating the TRANSFORM Role and assigning it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

--Creating a default Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

--Creating the 'dtb' user and assigning to the transform rols
CREATE USER IF NOT EXISTS dbt
PASSWORD='dbtpassword123'
LOGIN_NAME='dbt'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE='COMPUTE_WH'
DEFAULT_ROLE=TRANSFORM
DEFAULT_NAMESPACE='MOVIELENS.RAW'
COMMENT='DBT User used for data transformations';
  --Altering the user to set the type
ALTER USER DBT SET TYPE=LEGACY_SERVICE;
  --Granting roles to the user
GRANT ROLE TRANSFORM TO USER dbt

--Creating a database and schema for the movielens project
CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

--Granting permission to the 'transform' role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MOVIELENS TO ROLE TRANSFORM;
GRANT USAGE ON SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
-- Granting specific CREATE privileges on the schema
GRANT CREATE TABLE ON SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT CREATE VIEW ON SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;


-- Table-level permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE TRANSFORM;

